#!/bin/sh

regex='^[0-9]+\.[0-9]+\.[0-9]+ (Feature|Libraryfix|Glitchfix|Code Cleanup|Documentation|Changelog|Tasks?|Features?|Bugfixe?s?|Updates?|Releases?|Others?)(:.*)?'
msg="$( head -1 $1 )"

check=$(echo "$msg" | grep -E "$regex")
if [ "" = "$check" ]; then
        echo "Commit message invalid." 1>&2
        echo "Required format:" 1>&2
        echo "    $regex" 1>&2
        echo "Actual Message;"  1>&2
        echo "    $msg"
        exit 1
fi
