language: java

sudo: false

jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install: ./gradlew jar

script: 
 - ./gradlew check

notifications:
  email:
    recipients:
      - mailport@mikescher.de
    on_success: always
    on_failure: always