
# https://docs.gitea.com/next/usage/actions/quickstart
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

name: Build Docker and Deploy
run-name: Build & Deploy ${{ gitea.ref }} on ${{ gitea.actor }}

on: [push]

jobs:
  run_tests:
    name: Run jClipCorn test suite
    runs-on: bfb-cicd-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run tests
        run: docker run --rm -it $(docker build -q . -f Dockerfile_tests || echo __err_build__)

