package de.jClipCorn.features.transactionLog;

public enum CCTransactionAction {
	MOVIE_CHANGE_VIEWED,
	EPISODE_CHANGE_VIEWED,

	MOVIE_USERRATING,
	EPISODE_USERRATING,
	SEASON_USERRATING,
	SERIES_USERRATING,

	MOVIE_USERCOMMENT,
	SERIES_USERCOMMENT,
	SEASON_USERCOMMENT,
	EPISODE_USERCOMMENT,

	MOVIE_ADDED,
	EPISODE_ADDED,
	SEASON_ADDED,
	SERIES_ADDED,

	MOVIE_DELETED,
	EPISODE_DELETED,
	SEASON_DELETED,
	SERIES_DELETED,
}
