package de.jClipCorn.database.migration;

import de.jClipCorn.database.driver.GenericDatabase;
import de.jClipCorn.features.log.CCLog;
import de.jClipCorn.properties.CCProperties;
import de.jClipCorn.util.filesystem.FSPath;

import java.util.ArrayList;
import java.util.List;

public class Migration_17_18 extends DBMigration {

	public Migration_17_18(GenericDatabase db, CCProperties ccprops, FSPath databaseDirectory, String databaseName, boolean readonly) {
		super(db, ccprops, databaseDirectory, databaseName, readonly);
	}

	@Override
	public String getFromVersion() {
		return "17";
	}

	@Override
	public String getToVersion() {
		return "18";
	}

	@Override
	protected boolean backupAndRestoreTrigger() {
		return true;
	}

	@Override
	@SuppressWarnings("nls")
	protected List<UpgradeAction> run() throws Exception {
		CCLog.addInformation("[UPGRADE v17 -> v18] Add MEDIAINFO.CHECKSUM column to MAIN");
		CCLog.addInformation("[UPGRADE v17 -> v18] Add MEDIAINFO.CHECKSUM column to EPISODES");

		db.executeSQLThrow("CREATE TABLE \"___t1\" (   \"LOCALID\" INTEGER,   \"NAME\" VARCHAR(128) NOT NULL,   \"VIEWED_HISTORY\" VARCHAR(4096) NOT NULL,   \"ZYKLUS\" VARCHAR(128) NOT NULL,   \"ZYKLUSNUMBER\" INTEGER NOT NULL,   \"LANGUAGE\" BIGINT NOT NULL,   \"GENRE\" BIGINT NOT NULL,   \"LENGTH\" INTEGER NOT NULL,   \"ADDDATE\" DATE NOT NULL,   \"ONLINESCORE\" TINYINT NOT NULL,   \"FSK\" TINYINT NOT NULL,   \"FORMAT\" TINYINT NOT NULL,   \"MOVIEYEAR\" SMALLINT NOT NULL,   \"ONLINEREF\" VARCHAR(128) NOT NULL,   \"GROUPS\" VARCHAR(4096) NOT NULL,   \"FILESIZE\" BIGINT NOT NULL,   \"TAGS\" SMALLINT NOT NULL,   \"PART1\" VARCHAR(512) NOT NULL,   \"PART2\" VARCHAR(512) NOT NULL,   \"PART3\" VARCHAR(512) NOT NULL,   \"PART4\" VARCHAR(512) NOT NULL,   \"PART5\" VARCHAR(512) NOT NULL,   \"PART6\" VARCHAR(512) NOT NULL,   \"SCORE\" TINYINT NOT NULL,   \"COVERID\" INTEGER(256) NOT NULL,   \"TYPE\" TINYINT NOT NULL,   \"MEDIAINFO.FILESIZE\" BIGINT,   \"MEDIAINFO.CDATE\" BIGINT,   \"MEDIAINFO.MDATE\" BIGINT,   \"MEDIAINFO.AFORMAT\" VARCHAR(128),   \"MEDIAINFO.VFORMAT\" VARCHAR(128),   \"MEDIAINFO.WIDTH\" SMALLINT,   \"MEDIAINFO.HEIGHT\" SMALLINT,   \"MEDIAINFO.FRAMERATE\" REAL,   \"MEDIAINFO.DURATION\" REAL,   \"MEDIAINFO.BITDEPTH\" TINYINT,   \"MEDIAINFO.BITRATE\" INTEGER,   \"MEDIAINFO.FRAMECOUNT\" INTEGER,   \"MEDIAINFO.ACHANNELS\" INTEGER,   \"MEDIAINFO.VCODEC\" VARCHAR(128),   \"MEDIAINFO.ACODEC\" VARCHAR(128),   \"MEDIAINFO.SAMPLERATE\" INTEGER,   \"MEDIAINFO.CHECKSUM\" VARCHAR(1024),   PRIMARY KEY(\"LOCALID\")  )");
		db.executeSQLThrow("INSERT INTO \"___t1\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"TAGS\",\"TYPE\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"TAGS\",\"TYPE\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"ELEMENTS\"");
		db.executeSQLThrow("DROP TABLE \"ELEMENTS\";");
		db.executeSQLThrow("ALTER TABLE \"___t1\" RENAME TO \"ELEMENTS\"");

		db.executeSQLThrow("CREATE TABLE \"___t2\" ( \"LOCALID\" INTEGER, \"SEASONID\" INTEGER NOT NULL, \"EPISODE\" SMALLINT NOT NULL, \"NAME\" VARCHAR(128) NOT NULL, \"VIEWED_HISTORY\" VARCHAR(4096) NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"PART1\" VARCHAR(512) NOT NULL, \"ADDDATE\" DATE NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"LANGUAGE\" BIGINT, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" VARCHAR(128), \"MEDIAINFO.VFORMAT\" VARCHAR(128), \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" INTEGER, \"MEDIAINFO.VCODEC\" VARCHAR(128), \"MEDIAINFO.ACODEC\" VARCHAR(128), \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" VARCHAR(1024), PRIMARY KEY(\"LOCALID\"), FOREIGN KEY(\"SEASONID\") REFERENCES \"SEASONS\"(\"SEASONID\") );\n");
		db.executeSQLThrow("INSERT INTO \"___t2\" (\"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"TAGS\",\"VIEWED_HISTORY\") SELECT \"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"TAGS\",\"VIEWED_HISTORY\" FROM \"main\".\"EPISODES\"");
		db.executeSQLThrow("DROP TABLE \"EPISODES\";");
		db.executeSQLThrow("ALTER TABLE \"___t2\" RENAME TO \"EPISODES\"");

		db.executeSQLThrow("VACUUM");

		return new ArrayList<>();
	}
}
