package de.jClipCorn.database.migration;

import de.jClipCorn.database.driver.GenericDatabase;
import de.jClipCorn.features.log.CCLog;
import de.jClipCorn.properties.CCProperties;
import de.jClipCorn.util.filesystem.FSPath;

import java.util.ArrayList;
import java.util.List;

public class Migration_21_22 extends DBMigration {

	public Migration_21_22(GenericDatabase db, CCProperties ccprops, FSPath databaseDirectory, String databaseName, boolean readonly) {
		super(db, ccprops, databaseDirectory, databaseName, readonly);
	}

	@Override
	public String getFromVersion() {
		return "21";
	}

	@Override
	public String getToVersion() {
		return "22";
	}

	@Override
	protected boolean backupAndRestoreTrigger() {
		return true;
	}

	@Override
	@SuppressWarnings("nls")
	protected List<UpgradeAction> run() throws Exception {
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORECOMMENT in MOVIES");
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORECOMMENT in SERIES");
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORE in SEASONS");
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORECOMMENT in SEASONS");
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORE in EPISODES");
		CCLog.addInformation("[UPGRADE v21 -> v22] Add column SCORECOMMENT in EPISODES");

		db.executeSQLThrow("ALTER TABLE \"main\".\"MOVIES\" ADD COLUMN \t\"SCORECOMMENT\"\tVARCHAR NOT NULL DEFAULT ''");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_1\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"ZYKLUS\" TEXT NOT NULL, \"ZYKLUSNUMBER\" INTEGER NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"ADDDATE\" DATE NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"MOVIEYEAR\" SMALLINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"PART1\" TEXT NOT NULL, \"PART2\" TEXT NOT NULL, \"PART3\" TEXT NOT NULL, \"PART4\" TEXT NOT NULL, \"PART5\" TEXT NOT NULL, \"PART6\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"SCORECOMMENT\" VARCHAR NOT NULL DEFAULT '', \"COVERID\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\") );");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_1\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
		db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_1\" RENAME TO \"MOVIES\"");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_2\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"ZYKLUS\" TEXT NOT NULL, \"ZYKLUSNUMBER\" INTEGER NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"ADDDATE\" DATE NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"MOVIEYEAR\" SMALLINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"PART1\" TEXT NOT NULL, \"PART2\" TEXT NOT NULL, \"PART3\" TEXT NOT NULL, \"PART4\" TEXT NOT NULL, \"PART5\" TEXT NOT NULL, \"PART6\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"SCORECOMMENT\" VARCHAR NOT NULL, \"COVERID\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\") );");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_2\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SCORECOMMENT\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SCORECOMMENT\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
		db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_2\" RENAME TO \"MOVIES\"");

		db.executeSQLThrow("ALTER TABLE \"main\".\"SERIES\" ADD COLUMN \t\"SCORECOMMENT\"\tVARCHAR NOT NULL DEFAULT ''");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_3\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"SCORECOMMENT\" TEXT NOT NULL DEFAULT '', \"COVERID\" INTEGER NOT NULL, \"TAGS\" SMALLINT NOT NULL, PRIMARY KEY(\"LOCALID\") );\n");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_3\" (\"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\") SELECT \"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\" FROM \"main\".\"SERIES\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"SERIES\"");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_3\" RENAME TO \"SERIES\"");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_4\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"SCORECOMMENT\" TEXT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"TAGS\" SMALLINT NOT NULL, PRIMARY KEY(\"LOCALID\") );\n");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_4\" (\"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"SCORECOMMENT\",\"TAGS\") SELECT \"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"SCORECOMMENT\",\"TAGS\" FROM \"main\".\"SERIES\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"SERIES\"\n");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_4\" RENAME TO \"SERIES\"\n");

		db.executeSQLThrow("ALTER TABLE \"main\".\"SEASONS\" ADD COLUMN \t\"SCORE\"\tTINYINT NOT NULL DEFAULT 6");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_5\" ( \"LOCALID\" INTEGER, \"SERIESID\" INTEGER NOT NULL, \"NAME\" TEXT NOT NULL, \"SEASONYEAR\" SMALLINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"SCORE\" TINYINT NOT NULL DEFAULT 6, \"SCORECOMMENT\" VARCHAR NOT NULL DEFAULT '', PRIMARY KEY(\"LOCALID\"), FOREIGN KEY(\"SERIESID\") REFERENCES \"SERIES\"(\"LOCALID\") );");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_5\" (\"COVERID\",\"LOCALID\",\"NAME\",\"SEASONYEAR\",\"SERIESID\") SELECT \"COVERID\",\"LOCALID\",\"NAME\",\"SEASONYEAR\",\"SERIESID\" FROM \"main\".\"SEASONS\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"SEASONS\"\n");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_5\" RENAME TO \"SEASONS\"");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_6\" ( \"LOCALID\" INTEGER, \"SERIESID\" INTEGER NOT NULL, \"NAME\" TEXT NOT NULL, \"SEASONYEAR\" SMALLINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"SCORE\" TINYINT NOT NULL, \"SCORECOMMENT\" VARCHAR NOT NULL, FOREIGN KEY(\"SERIESID\") REFERENCES \"SERIES\"(\"LOCALID\"), PRIMARY KEY(\"LOCALID\") );\n");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_6\" (\"COVERID\",\"LOCALID\",\"NAME\",\"SCORE\",\"SCORECOMMENT\",\"SEASONYEAR\",\"SERIESID\") SELECT \"COVERID\",\"LOCALID\",\"NAME\",\"SCORE\",\"SCORECOMMENT\",\"SEASONYEAR\",\"SERIESID\" FROM \"main\".\"SEASONS\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"SEASONS\"\n");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_6\" RENAME TO \"SEASONS\"\n");

		db.executeSQLThrow("ALTER TABLE \"main\".\"EPISODES\" ADD COLUMN \t\"SCORE\"\tINTEGER NOT NULL DEFAULT 6\n");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_7\" ( \"LOCALID\" INTEGER, \"SEASONID\" INTEGER NOT NULL, \"EPISODE\" SMALLINT NOT NULL, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"PART1\" TEXT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"ADDDATE\" DATE NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"SCORE\" INTEGER NOT NULL DEFAULT 6, \"SCORECOMMENT\" INTEGER NOT NULL DEFAULT '', \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, FOREIGN KEY(\"SEASONID\") REFERENCES \"SEASONS\"(\"LOCALID\"), PRIMARY KEY(\"LOCALID\") );\n");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_7\" (\"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\") SELECT \"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\" FROM \"main\".\"EPISODES\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"EPISODES\"\n");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_7\" RENAME TO \"EPISODES\"\n");
		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_8\" ( \"LOCALID\" INTEGER, \"SEASONID\" INTEGER NOT NULL, \"EPISODE\" SMALLINT NOT NULL, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"PART1\" TEXT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"ADDDATE\" DATE NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"SCORE\" INTEGER NOT NULL, \"SCORECOMMENT\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, FOREIGN KEY(\"SEASONID\") REFERENCES \"SEASONS\"(\"LOCALID\"), PRIMARY KEY(\"LOCALID\") );\n");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_8\" (\"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SCORE\",\"SCORECOMMENT\",\"SEASONID\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\") SELECT \"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SCORE\",\"SCORECOMMENT\",\"SEASONID\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\" FROM \"main\".\"EPISODES\"\n");
		db.executeSQLThrow("DROP TABLE \"main\".\"EPISODES\"\n");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_8\" RENAME TO \"EPISODES\"\n");

		return new ArrayList<>();
	}
}
