package de.jClipCorn.database.migration;

import de.jClipCorn.database.driver.GenericDatabase;
import de.jClipCorn.database.history.CCDatabaseHistory;
import de.jClipCorn.features.log.CCLog;
import de.jClipCorn.properties.CCProperties;
import de.jClipCorn.util.filesystem.FSPath;
import de.jClipCorn.util.stream.CCStreams;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class Migration_20_21 extends DBMigration {

	public Migration_20_21(GenericDatabase db, CCProperties ccprops, FSPath databaseDirectory, String databaseName, boolean readonly) {
		super(db, ccprops, databaseDirectory, databaseName, readonly);
	}

	@Override
	public String getFromVersion() {
		return "20";
	}

	@Override
	public String getToVersion() {
		return "21";
	}

	@Override
	@SuppressWarnings("nls")
	public List<UpgradeAction> migrate() throws Exception {
		CCLog.addInformation("[UPGRADE v20 -> v21] Rename ONLINESCORE to ONLINESCORE_NUM in MOVIES");
		CCLog.addInformation("[UPGRADE v20 -> v21] Add ONLINESCORE_DENOM column to MOVIES");
		CCLog.addInformation("[UPGRADE v20 -> v21] Rename ONLINESCORE to ONLINESCORE_NUM in SERIES");
		CCLog.addInformation("[UPGRADE v20 -> v21] Add ONLINESCORE_DENOM column to SERIES");

		db.executeSQLThrow("BEGIN TRANSACTION");
		db.executeSQLThrow("PRAGMA foreign_keys = OFF;");
		{
			for (String trigger : CCStreams.iterate(db.listTrigger()).filter(t -> t.startsWith("JCCTRIGGER_")))
			{
				db.executeSQLThrow("DROP TRIGGER ["+trigger+"]");
			}

			db.executeSQLThrow("ALTER TABLE \"MOVIES\" RENAME COLUMN \"ONLINESCORE\" TO \"ONLINESCORE_NUM\"");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_1\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"ZYKLUS\" TEXT NOT NULL, \"ZYKLUSNUMBER\" INTEGER NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"ADDDATE\" DATE NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"MOVIEYEAR\" SMALLINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"PART1\" TEXT NOT NULL, \"PART2\" TEXT NOT NULL, \"PART3\" TEXT NOT NULL, \"PART4\" TEXT NOT NULL, \"PART5\" TEXT NOT NULL, \"PART6\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_1\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_1\" RENAME TO \"MOVIES\"");

			db.executeSQLThrow("ALTER TABLE \"main\".\"MOVIES\" ADD COLUMN \t\"ONLINESCORE_DENOM\"\tSMALLINT NOT NULL DEFAULT 10");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_2\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"ZYKLUS\" TEXT NOT NULL, \"ZYKLUSNUMBER\" INTEGER NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"ADDDATE\" DATE NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL DEFAULT 10, \"FSK\" TINYINT NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"MOVIEYEAR\" SMALLINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"PART1\" TEXT NOT NULL, \"PART2\" TEXT NOT NULL, \"PART3\" TEXT NOT NULL, \"PART4\" TEXT NOT NULL, \"PART5\" TEXT NOT NULL, \"PART6\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_2\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_2\" RENAME TO \"MOVIES\"");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_3\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"ZYKLUS\" TEXT NOT NULL, \"ZYKLUSNUMBER\" INTEGER NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"ADDDATE\" DATE NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"MOVIEYEAR\" SMALLINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"PART1\" TEXT NOT NULL, \"PART2\" TEXT NOT NULL, \"PART3\" TEXT NOT NULL, \"PART4\" TEXT NOT NULL, \"PART5\" TEXT NOT NULL, \"PART6\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" SMALLINT, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_3\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"SUBTITLES\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_3\" RENAME TO \"MOVIES\"");

			db.executeSQLThrow("ALTER TABLE \"main\".\"SERIES\" RENAME COLUMN \"ONLINESCORE\" TO \"ONLINESCORE_NUM\"");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_4\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"ONLINESCORE_NUM\" TINYINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"TAGS\" SMALLINT NOT NULL, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_4\" (\"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\") SELECT \"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\" FROM \"main\".\"SERIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"SERIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_4\" RENAME TO \"SERIES\"");

			db.executeSQLThrow("ALTER TABLE \"main\".\"SERIES\" ADD COLUMN \t\"ONLINESCORE_DENOM\"\tSMALLINT NOT NULL DEFAULT 10");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_5\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL DEFAULT 10, \"FSK\" TINYINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"TAGS\" SMALLINT NOT NULL, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_5\" (\"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\") SELECT \"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\" FROM \"main\".\"SERIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"SERIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_5\" RENAME TO \"SERIES\"");

			db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_6\" ( \"LOCALID\" INTEGER, \"NAME\" TEXT NOT NULL, \"GENRE\" BIGINT NOT NULL, \"ONLINESCORE_NUM\" SMALLINT NOT NULL, \"ONLINESCORE_DENOM\" SMALLINT NOT NULL, \"FSK\" TINYINT NOT NULL, \"ONLINEREF\" TEXT NOT NULL, \"GROUPS\" TEXT NOT NULL, \"SCORE\" TINYINT NOT NULL, \"COVERID\" INTEGER NOT NULL, \"TAGS\" SMALLINT NOT NULL, PRIMARY KEY(\"LOCALID\") );");
			db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_6\" (\"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\") SELECT \"COVERID\",\"FSK\",\"GENRE\",\"GROUPS\",\"LOCALID\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE_DENOM\",\"ONLINESCORE_NUM\",\"SCORE\",\"TAGS\" FROM \"main\".\"SERIES\"");
			db.executeSQLThrow("DROP TABLE \"main\".\"SERIES\"");
			db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_6\" RENAME TO \"SERIES\"");

			if (db.querySingleStringSQL("SELECT IVALUE FROM INFO WHERE IKEY = 'HISTORY_ENABLED'", 0).equals("1"))
			{
				for (var trigger : CCDatabaseHistory.createTriggerStatements()) db.executeSQLThrow(trigger.Item2);
			}
		}
		db.executeSQLThrow("PRAGMA foreign_keys = ON;");
		db.executeSQLThrow("COMMIT TRANSACTION");

		db.executeSQLThrow("VACUUM");

		return new ArrayList<>();
	}
}
