package de.jClipCorn.database.migration;

import de.jClipCorn.database.driver.GenericDatabase;
import de.jClipCorn.features.log.CCLog;
import de.jClipCorn.properties.CCProperties;
import de.jClipCorn.util.filesystem.FSPath;

import java.util.ArrayList;
import java.util.List;

public class Migration_19_20 extends DBMigration {

	public Migration_19_20(GenericDatabase db, CCProperties ccprops, FSPath databaseDirectory, String databaseName, boolean readonly) {
		super(db, ccprops, databaseDirectory, databaseName, readonly);
	}

	@Override
	public String getFromVersion() {
		return "19";
	}

	@Override
	public String getToVersion() {
		return "20";
	}

	@Override
	protected boolean backupAndRestoreTrigger() {
		return true;
	}

	@Override
	@SuppressWarnings("nls")
	protected List<UpgradeAction> run() throws Exception {
		CCLog.addInformation("[UPGRADE v19 -> v20] Add SUBTITLES column to MOVIES");
		CCLog.addInformation("[UPGRADE v19 -> v20] Add SUBTITLES column to EPISODES");

		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_1\" (  \"LOCALID\" INTEGER,  \"NAME\" TEXT NOT NULL,  \"VIEWED_HISTORY\" TEXT NOT NULL,  \"ZYKLUS\" TEXT NOT NULL,  \"ZYKLUSNUMBER\" INTEGER NOT NULL,  \"LANGUAGE\" BIGINT NOT NULL,  \"SUBTITLES\" TEXT NOT NULL DEFAULT \"\",  \"GENRE\" BIGINT NOT NULL,  \"LENGTH\" INTEGER NOT NULL,  \"ADDDATE\" DATE NOT NULL,  \"ONLINESCORE\" TINYINT NOT NULL,  \"FSK\" TINYINT NOT NULL,  \"FORMAT\" TINYINT NOT NULL,  \"MOVIEYEAR\" SMALLINT NOT NULL,  \"ONLINEREF\" TEXT NOT NULL,  \"GROUPS\" TEXT NOT NULL,  \"FILESIZE\" BIGINT NOT NULL,  \"TAGS\" SMALLINT NOT NULL,  \"PART1\" TEXT NOT NULL,  \"PART2\" TEXT NOT NULL,  \"PART3\" TEXT NOT NULL,  \"PART4\" TEXT NOT NULL,  \"PART5\" TEXT NOT NULL,  \"PART6\" TEXT NOT NULL,  \"SCORE\" TINYINT NOT NULL,  \"COVERID\" INTEGER NOT NULL,  \"MEDIAINFO.FILESIZE\" BIGINT,  \"MEDIAINFO.CDATE\" BIGINT,  \"MEDIAINFO.MDATE\" BIGINT,  \"MEDIAINFO.AFORMAT\" TEXT,  \"MEDIAINFO.VFORMAT\" TEXT,  \"MEDIAINFO.WIDTH\" SMALLINT,  \"MEDIAINFO.HEIGHT\" SMALLINT,  \"MEDIAINFO.FRAMERATE\" REAL,  \"MEDIAINFO.DURATION\" REAL,  \"MEDIAINFO.BITDEPTH\" TINYINT,  \"MEDIAINFO.BITRATE\" INTEGER,  \"MEDIAINFO.FRAMECOUNT\" INTEGER,  \"MEDIAINFO.ACHANNELS\" INTEGER,  \"MEDIAINFO.VCODEC\" TEXT,  \"MEDIAINFO.ACODEC\" TEXT,  \"MEDIAINFO.SAMPLERATE\" INTEGER,  \"MEDIAINFO.CHECKSUM\" TEXT,  PRIMARY KEY(\"LOCALID\") );");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_1\" (\"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\") SELECT \"ADDDATE\",\"COVERID\",\"FILESIZE\",\"FORMAT\",\"FSK\",\"GENRE\",\"GROUPS\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"MOVIEYEAR\",\"NAME\",\"ONLINEREF\",\"ONLINESCORE\",\"PART1\",\"PART2\",\"PART3\",\"PART4\",\"PART5\",\"PART6\",\"SCORE\",\"TAGS\",\"VIEWED_HISTORY\",\"ZYKLUS\",\"ZYKLUSNUMBER\" FROM \"main\".\"MOVIES\"");
		db.executeSQLThrow("DROP TABLE \"main\".\"MOVIES\"");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_1\" RENAME TO \"MOVIES\"");

		db.executeSQLThrow("CREATE TABLE \"sqlb_temp_table_2\" ( \"LOCALID\" INTEGER, \"SEASONID\" INTEGER NOT NULL, \"EPISODE\" SMALLINT NOT NULL, \"NAME\" TEXT NOT NULL, \"VIEWED_HISTORY\" TEXT NOT NULL, \"LENGTH\" INTEGER NOT NULL, \"FORMAT\" TINYINT NOT NULL, \"FILESIZE\" BIGINT NOT NULL, \"PART1\" TEXT NOT NULL, \"TAGS\" SMALLINT NOT NULL, \"ADDDATE\" DATE NOT NULL, \"LANGUAGE\" BIGINT NOT NULL, \"SUBTITLES\" TEXT NOT NULL DEFAULT \"\", \"MEDIAINFO.FILESIZE\" BIGINT, \"MEDIAINFO.CDATE\" BIGINT, \"MEDIAINFO.MDATE\" BIGINT, \"MEDIAINFO.AFORMAT\" TEXT, \"MEDIAINFO.VFORMAT\" TEXT, \"MEDIAINFO.WIDTH\" SMALLINT, \"MEDIAINFO.HEIGHT\" SMALLINT, \"MEDIAINFO.FRAMERATE\" REAL, \"MEDIAINFO.DURATION\" REAL, \"MEDIAINFO.BITDEPTH\" TINYINT, \"MEDIAINFO.BITRATE\" INTEGER, \"MEDIAINFO.FRAMECOUNT\" INTEGER, \"MEDIAINFO.ACHANNELS\" INTEGER, \"MEDIAINFO.VCODEC\" TEXT, \"MEDIAINFO.ACODEC\" TEXT, \"MEDIAINFO.SAMPLERATE\" INTEGER, \"MEDIAINFO.CHECKSUM\" TEXT, PRIMARY KEY(\"LOCALID\"), FOREIGN KEY(\"SEASONID\") REFERENCES \"SEASONS\"(\"LOCALID\") );");
		db.executeSQLThrow("INSERT INTO \"main\".\"sqlb_temp_table_2\" (\"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"TAGS\",\"VIEWED_HISTORY\") SELECT \"ADDDATE\",\"EPISODE\",\"FILESIZE\",\"FORMAT\",\"LANGUAGE\",\"LENGTH\",\"LOCALID\",\"MEDIAINFO.ACHANNELS\",\"MEDIAINFO.ACODEC\",\"MEDIAINFO.AFORMAT\",\"MEDIAINFO.BITDEPTH\",\"MEDIAINFO.BITRATE\",\"MEDIAINFO.CDATE\",\"MEDIAINFO.CHECKSUM\",\"MEDIAINFO.DURATION\",\"MEDIAINFO.FILESIZE\",\"MEDIAINFO.FRAMECOUNT\",\"MEDIAINFO.FRAMERATE\",\"MEDIAINFO.HEIGHT\",\"MEDIAINFO.MDATE\",\"MEDIAINFO.SAMPLERATE\",\"MEDIAINFO.VCODEC\",\"MEDIAINFO.VFORMAT\",\"MEDIAINFO.WIDTH\",\"NAME\",\"PART1\",\"SEASONID\",\"TAGS\",\"VIEWED_HISTORY\" FROM \"main\".\"EPISODES\"");
		db.executeSQLThrow("DROP TABLE \"main\".\"EPISODES\"");
		db.executeSQLThrow("ALTER TABLE \"main\".\"sqlb_temp_table_2\" RENAME TO \"EPISODES\"");

		return new ArrayList<>();
	}
}
